#!/bin/sh
# generate modules.h: embeds every file under modules/ as a C string.
# blk_cmd("name.sh", ...) runs the embedded text through sh at runtime.
echo "/* generated by gen-modules.sh from modules/ - do not edit */"
names=""
for f in modules/*; do
	[ -f "$f" ] || continue
	base=$(basename "$f")
	id=$(printf %s "$base" | tr -c 'a-zA-Z0-9' '_')
	printf 'static const char mod_%s[] =\n' "$id"
	sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$/\\n"/' "$f"
	printf ';\n'
	names="$names	{ \"$base\", mod_$id },\n"
done
printf 'static const struct module { const char *name, *text; } modules[] = {\n'
printf "$names"
printf '	{ 0, 0 },\n};\n'
